apiVersion: v1
kind: Service
metadata:
  name: sentinel-backend
  namespace: sentinelai
spec:
  selector:
    app: sentinel-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
