"use client"

import { use } from "react"
import Link from "next/link"
import { AppHeader } from "@/components/app-header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { ScrollArea } from "@/components/ui/scroll-area"
import { ArrowLeft, GitPullRequest, GitBranch, CheckCircle, Circle, Loader2, Clock, FileCode, GitMerge } from "lucide-react"

interface PatchDetail {
  cve: string
  component: string
  patchType: string
  commitMessage: string
  branch: string
  prStatus: string
  ciResult: string
  diff: string
  author: string
  createdAt: string
  lastUpdated: string
  testsRun: number
  testsPassed: number
  reviewers: string[]
  ciSteps: { step: string; status: string; duration: string }[]
  changelog: { time: string; event: string }[]
}

const patches: Record<string, PatchDetail> = {
  "CVE-2026-21001": {
    cve: "CVE-2026-21001", component: "OpenSSL 3.1.4", patchType: "Dependency Upgrade",
    commitMessage: "fix(security): patch OpenSSL buffer overflow CVE-2026-21001",
    branch: "security/CVE-2026-21001", prStatus: "Open", ciResult: "Passing",
    diff: `--- a/requirements.txt\n+++ b/requirements.txt\n@@ -12,7 +12,7 @@\n-openssl==3.1.4\n+openssl==3.1.5\n\n--- a/ssl/statem/extensions_clnt.c\n+++ b/ssl/statem/extensions_clnt.c\n@@ -412,7 +412,11 @@\n-    memcpy(session_ticket, data, len);\n+    if (len > MAX_SESSION_TICKET_LEN) {\n+        SSLfatal(s, SSL_AD_DECODE_ERROR,\n+                 SSL_R_TICKET_TOO_LONG);\n+        return 0;\n+    }\n+    memcpy(session_ticket, data, len);`,
    author: "SentinelAI Bot", createdAt: "2026-03-03 02:23 UTC", lastUpdated: "2026-03-03 02:45 UTC",
    testsRun: 342, testsPassed: 342, reviewers: ["security-team", "platform-team"],
    ciSteps: [
      { step: "Lint", status: "passed", duration: "12s" },
      { step: "Unit Tests", status: "passed", duration: "1m 42s" },
      { step: "Integration Tests", status: "passed", duration: "3m 18s" },
      { step: "Security Scan", status: "passed", duration: "2m 05s" },
      { step: "Build", status: "passed", duration: "45s" },
    ],
    changelog: [
      { time: "02:22 UTC", event: "Patch auto-generated by SentinelAI" },
      { time: "02:23 UTC", event: "Pull request created on security/CVE-2026-21001" },
      { time: "02:24 UTC", event: "CI pipeline triggered" },
      { time: "02:32 UTC", event: "All CI checks passed" },
      { time: "02:33 UTC", event: "Review requested from security-team, platform-team" },
      { time: "02:45 UTC", event: "Awaiting human approval to merge" },
    ],
  },
  "CVE-2026-18823": {
    cve: "CVE-2026-18823", component: "log4j-core 2.17.1", patchType: "Dependency Upgrade",
    commitMessage: "fix(security): upgrade log4j-core to mitigate JNDI injection CVE-2026-18823",
    branch: "security/CVE-2026-18823", prStatus: "Open", ciResult: "Passing",
    diff: `--- a/pom.xml\n+++ b/pom.xml\n@@ -45,7 +45,7 @@\n-    <log4j.version>2.17.1</log4j.version>\n+    <log4j.version>2.21.0</log4j.version>`,
    author: "SentinelAI Bot", createdAt: "2026-03-03 01:51 UTC", lastUpdated: "2026-03-03 02:10 UTC",
    testsRun: 218, testsPassed: 218, reviewers: ["backend-team"],
    ciSteps: [
      { step: "Lint", status: "passed", duration: "8s" },
      { step: "Unit Tests", status: "passed", duration: "2m 12s" },
      { step: "Integration Tests", status: "passed", duration: "4m 01s" },
      { step: "Security Scan", status: "passed", duration: "1m 48s" },
      { step: "Build", status: "passed", duration: "1m 02s" },
    ],
    changelog: [
      { time: "01:50 UTC", event: "Patch auto-generated by SentinelAI" },
      { time: "01:51 UTC", event: "Pull request created on security/CVE-2026-18823" },
      { time: "01:52 UTC", event: "CI pipeline triggered" },
      { time: "02:00 UTC", event: "All CI checks passed" },
      { time: "02:10 UTC", event: "Awaiting human approval to merge" },
    ],
  },
}

function prStatusIcon(status: string) {
  switch (status) {
    case "Open": return <Circle className="h-4 w-4 text-success" />
    case "Draft": return <Circle className="h-4 w-4 text-warning" />
    case "Merged": return <GitMerge className="h-4 w-4 text-chart-1" />
    default: return <Circle className="h-4 w-4 text-muted-foreground" />
  }
}

function ciStepIcon(status: string) {
  switch (status) {
    case "passed": return <CheckCircle className="h-3.5 w-3.5 text-success" />
    case "running": return <Loader2 className="h-3.5 w-3.5 animate-spin text-chart-1" />
    default: return <Circle className="h-3.5 w-3.5 text-muted-foreground" />
  }
}

export default function PatchDetailPage({ params }: { params: Promise<{ cve: string }> }) {
  const { cve } = use(params)
  const decodedCve = decodeURIComponent(cve)
  const patch = patches[decodedCve]

  if (!patch) {
    return (
      <div className="flex flex-col">
        <AppHeader title="Patch Detail" />
        <div className="flex flex-col items-center justify-center gap-4 p-12">
          <p className="text-sm text-muted-foreground">Patch not found for: {decodedCve}</p>
          <Link href="/patch-automation">
            <Button variant="outline" size="sm" className="border-border bg-secondary text-secondary-foreground">
              <ArrowLeft className="mr-1.5 h-3.5 w-3.5" /> Back to Patch Automation
            </Button>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="flex flex-col">
      <AppHeader title={`Patch: ${patch.cve}`} />
      <div className="flex flex-col gap-6 p-6">
        <div className="flex items-center gap-2">
          <Link href="/patch-automation" className="flex items-center gap-1.5 text-xs text-muted-foreground transition-colors hover:text-foreground">
            <ArrowLeft className="h-3 w-3" /> Patch Automation
          </Link>
          <span className="text-xs text-muted-foreground">/</span>
          <span className="font-mono text-xs font-semibold text-card-foreground">{patch.cve}</span>
        </div>

        {/* Header */}
        <Card className="border-border bg-card">
          <CardContent className="flex items-start justify-between p-5">
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2">
                {prStatusIcon(patch.prStatus)}
                <div className="flex flex-col gap-1">
                  <span className="font-mono text-sm font-bold text-card-foreground">{patch.commitMessage}</span>
                  <div className="flex items-center gap-3 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1"><GitBranch className="h-3 w-3" /> <span className="font-mono text-primary">{patch.branch}</span></span>
                    <span className="flex items-center gap-1"><FileCode className="h-3 w-3" /> {patch.patchType}</span>
                    <span className="flex items-center gap-1"><Clock className="h-3 w-3" /> {patch.createdAt}</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {patch.prStatus === "Open" && (
                <Button size="sm" className="bg-primary text-primary-foreground hover:bg-primary/90">
                  <GitMerge className="mr-1.5 h-3.5 w-3.5" /> Approve & Merge
                </Button>
              )}
            </div>
          </CardContent>
        </Card>

        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
          <div className="flex flex-col gap-6 lg:col-span-2">
            {/* Diff */}
            <Card className="border-border bg-card">
              <CardHeader className="pb-3">
                <div className="flex items-center gap-2">
                  <GitPullRequest className="h-4 w-4 text-primary" />
                  <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Code Diff</CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <ScrollArea className="max-h-80">
                  <pre className="overflow-x-auto rounded-md border border-border bg-background p-4 font-mono text-xs leading-relaxed">
                    {patch.diff.split('\n').map((line, i) => (
                      <div key={i} className={line.startsWith('+') ? 'text-success' : line.startsWith('-') ? 'text-destructive' : line.startsWith('@@') ? 'text-primary' : 'text-muted-foreground'}>
                        {line}
                      </div>
                    ))}
                  </pre>
                </ScrollArea>
              </CardContent>
            </Card>

            {/* CI Pipeline */}
            <Card className="border-border bg-card">
              <CardHeader className="pb-3">
                <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">CI Pipeline Results</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="mb-3 flex items-center gap-2 text-xs">
                  <Badge variant="outline" className="bg-success/10 text-success border-success/20">
                    {patch.testsPassed}/{patch.testsRun} Tests Passed
                  </Badge>
                </div>
                <div className="flex flex-col gap-2">
                  {patch.ciSteps.map((step) => (
                    <div key={step.step} className="flex items-center justify-between rounded-md border border-border bg-secondary/50 p-2.5">
                      <div className="flex items-center gap-2">
                        {ciStepIcon(step.status)}
                        <span className="text-xs font-medium text-card-foreground">{step.step}</span>
                      </div>
                      <span className="font-mono text-[10px] text-muted-foreground">{step.duration}</span>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          <div className="flex flex-col gap-6">
            {/* Metadata */}
            <Card className="border-border bg-card">
              <CardHeader className="pb-3">
                <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Details</CardTitle>
              </CardHeader>
              <CardContent className="flex flex-col gap-3 text-xs">
                <div><span className="text-muted-foreground">Author:</span> <span className="ml-1 text-card-foreground">{patch.author}</span></div>
                <Separator className="bg-border" />
                <div><span className="text-muted-foreground">Component:</span> <span className="ml-1 font-mono text-card-foreground">{patch.component}</span></div>
                <Separator className="bg-border" />
                <div><span className="text-muted-foreground">Reviewers:</span> <span className="ml-1 text-card-foreground">{patch.reviewers.join(", ")}</span></div>
                <Separator className="bg-border" />
                <div><span className="text-muted-foreground">Last Updated:</span> <span className="ml-1 font-mono text-card-foreground">{patch.lastUpdated}</span></div>
              </CardContent>
            </Card>

            {/* Changelog */}
            <Card className="border-border bg-card">
              <CardHeader className="pb-3">
                <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Activity Log</CardTitle>
              </CardHeader>
              <CardContent className="flex flex-col gap-2">
                {patch.changelog.map((entry, i) => (
                  <div key={i} className="flex gap-3 text-xs">
                    <span className="w-16 shrink-0 font-mono text-muted-foreground">{entry.time}</span>
                    <span className="text-card-foreground">{entry.event}</span>
                  </div>
                ))}
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  )
}
