events { worker_connections 1024; }

http {
  upstream storefront { server shopvault-storefront:3000; }
  upstream catalog { server product-catalog-api:3000; }
  upstream admin { server admin-portal:3000; }

  server {
    listen 80;
    server_name _;

    location /health {
      return 200 '{"status":"ok","service":"nginx-cdn-proxy"}';
      add_header Content-Type application/json;
    }

    location /api/v1/products {
      proxy_pass http://catalog;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /admin/ {
      proxy_pass http://admin;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      proxy_pass http://storefront;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
